---
apiVersion: apps/v1
metadata:
    name:netology-ml
spec:
    replicas: 2
    strategy:
        type: RollingUpdate
    template:
        spec:
        containers:
            - image: tomcat:8.5.69
            name: tomcat
               ports:
                    - containerPort: 8080